title:             Dia a Dia con Sap Business One
email:             david@davidpalazon.net
description:       Un blog sobre las vivencias de un consultor Sap B1
author:            David Palazón
baseurl:           ""
url:               "https://palpid.github.io"

# Social Profiles
twitter_username:  DavidBermd
github_username:   palpid
facebook_username: palpid

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
